DROP DATABASE if exists Delfinen;
CREATE DATABASE DELFINEN;
USE DELFINEN;

CREATE TABLE MEMBERS (
	MEMBER_NAME VARCHAR(50) NOT NULL,
    AGE INT NOT NULL,
    SUBSCRIPTION INT NULL,
    ACTIVE TINYINT NULL,
    ARREARS TINYINT NULL,
    MEMBER_ID INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (MEMBER_ID)
);

CREATE TABLE COMPETITION_SWIMMERS (
	DISCIPLINES VARCHAR(120) NOT NULL,
    COACH_ID INT NOT NULL,
    MEMBER_ID INT NOT NULL,
    FOREIGN KEY (MEMBER_ID)
		REFERENCES MEMBERS (MEMBER_ID),
	FOREIGN KEY (COACH_ID)
		REFERENCES MEMBERS (MEMBER_ID)
);

CREATE TABLE COMPETITION_RESULTS (
	EVENT_NAME VARCHAR(50) NOT NULL,
	DISCIPLINE VARCHAR(50) NOT NULL,
    EVENT_DATE DATE NOT NULL,
    BEST_TIME TIME NOT NULL,
    PLACEMENT INT NOT NULL,
    MEMBER_ID INT NOT NULL,
    COMPETITION_ID INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (COMPETITION_ID),
    FOREIGN KEY (MEMBER_ID)
		REFERENCES MEMBERS (MEMBER_ID)
);

CREATE TABLE TRAINING_RESULTS (
	DISCIPLINE VARCHAR(50) NOT NULL,
    TRAINING_DATE DATE NOT NULL,
    BEST_TIME TIME NOT NULL,
    MEMBER_ID INT NOT NULL,
    TRAINING_ID INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (TRAINING_ID),
    FOREIGN KEY (MEMBER_ID)
		REFERENCES MEMBERS (MEMBER_ID)
);

COMMIT;
    

