-- INSERT DISCIPLINES
INSERT INTO DISCIPLINES (DISCIPLINE_NAME, DISCIPLINE_ID) VALUES ('BUTTERFLY', 1);
INSERT INTO DISCIPLINES (DISCIPLINE_NAME, DISCIPLINE_ID) VALUES ('CRAWL', 2);
INSERT INTO DISCIPLINES (DISCIPLINE_NAME, DISCIPLINE_ID) VALUES ('BACKSTROKE', 3);
INSERT INTO DISCIPLINES (DISCIPLINE_NAME, DISCIPLINE_ID) VALUES ('BREASTSTROKE', 4);

-- INSERT INTO MEMBERS
INSERT INTO MEMBERS (MEMBER_NAME, AGE, SUBSCRIPTION, ACTIVE, ARREARS, MEMBER_ID) VALUES ('Mads Brandt', 25, 1600, 1, 0, 1); -- Senior member, competition swimmer
INSERT INTO MEMBERS (MEMBER_NAME, AGE, SUBSCRIPTION, ACTIVE, ARREARS, MEMBER_ID) VALUES ('Alexander Sarson', 29, 1600, 1, 1, 2); -- Motionist
INSERT INTO MEMBERS (MEMBER_NAME, AGE, ACTIVE, ARREARS, MEMBER_ID) VALUES ('Benjamin Paepke', 27, 1, 0, 3); -- Coach
INSERT INTO MEMBERS (MEMBER_NAME, AGE, SUBSCRIPTION, ACTIVE, ARREARS, MEMBER_ID) VALUES ('Tobias Boldt-Jørgensen', 15, 1000, 1, 0, 4); -- Junior member
INSERT INTO MEMBERS (MEMBER_NAME, AGE, SUBSCRIPTION, ACTIVE, ARREARS, MEMBER_ID, COACH_ID) VALUES ('Senior Swimmer', 30, 1600, 1, 0, 5, 3); -- Senior member
INSERT INTO MEMBERS (MEMBER_NAME, AGE, SUBSCRIPTION, ACTIVE, ARREARS, MEMBER_ID, COACH_ID) VALUES ('Junior Swimmer', 15, 1000, 1, 0, 6, 3); -- junior member
INSERT INTO MEMBERS (MEMBER_NAME, AGE, SUBSCRIPTION, ACTIVE, ARREARS, MEMBER_ID) VALUES ('Old Member', 70, 1200, 1, 1, 7); -- old member

-- Insert Swimmer' training results
INSERT INTO TRAINING_RESULTS (DISCIPLINE_ID, TRAINING_DATE, BEST_TIME, MEMBER_ID) VALUES (1, '2019-03-22', '00:02:03', 5);
INSERT INTO TRAINING_RESULTS (DISCIPLINE_ID, TRAINING_DATE, BEST_TIME, MEMBER_ID) VALUES (2, '2019-03-22', '00:02:40', 5);
INSERT INTO TRAINING_RESULTS (DISCIPLINE_ID, TRAINING_DATE, BEST_TIME, MEMBER_ID) VALUES (3, '2019-02-22', '00:03:03', 6);
INSERT INTO TRAINING_RESULTS (DISCIPLINE_ID, TRAINING_DATE, BEST_TIME, MEMBER_ID) VALUES (4, '2019-02-22', '00:04:40', 6);

-- Insert competition results.. 
INSERT INTO COMPETITION_RESULTS (EVENT_NAME, DISCIPLINE_ID, EVENT_DATE, BEST_TIME, PLACEMENT, MEMBER_ID) VALUES ('DM', 1, '2019-04-01', '00:01:54', 1, 5);
INSERT INTO COMPETITION_RESULTS (EVENT_NAME, DISCIPLINE_ID, EVENT_DATE, BEST_TIME, PLACEMENT, MEMBER_ID) VALUES ('DM', 4, '2019-04-01', '00:04:30', 6, 5);
INSERT INTO COMPETITION_RESULTS (EVENT_NAME, DISCIPLINE_ID, EVENT_DATE, BEST_TIME, PLACEMENT, MEMBER_ID) VALUES ('DM', 3, '2019-04-01', '00:05:54', 7, 6);
INSERT INTO COMPETITION_RESULTS (EVENT_NAME, DISCIPLINE_ID, EVENT_DATE, BEST_TIME, PLACEMENT, MEMBER_ID) VALUES ('DM', 2, '2019-04-01', '00:07:30', 9, 6);

SELECT * FROM COMPETITION_RESULTS;